#!/bin/bash -e
##coverage <files.txt>
## files.txt is path of positionally sorted and indexed bams
## name.bam > bamstats04 > awk > name.coverage
## may want to add mapq and length filters for the reads.

input=${1}
echo -e "filter\tsample\tCHROM\tPOS\tcoverage" > "coverage.txt"
while read -r line
do

if [[ ! $line =~ ^# ]];then
	pi=$(dirname "${line}")
	fp=$(basename "$line")
        [ ${fp%%*.} == "gz" ] && { fn=${fp%.gz}; fe="gz"; } || { fn=${fp%.fastq.gz}; fe="fastq.gz"; }
        [ ${fp%%*.} == "fastq" ] && { fn=${fp%.fastq}; fe="fastq"; }
        [[ $fe != "fastq.gz" && $fe != "fastq" ]] && { echo "Bad file extention for $fp, must be .fastq or .fastq.gz"; exit 1; }
java -jar /NGS/downloads/jvarkit/dist/bamstats04.jar -B VarDict-amplicon.bed "${pi}/${fn}-good.bam" > "${pi}/${fn}-NT.coverage"
java -jar /NGS/downloads/jvarkit/dist/bamstats04.jar -B VarDict-amplicon.bed "${pi}/${fn}-IS.bam" > "${pi}/${fn}-IS.coverage"
java -jar /NGS/downloads/jvarkit/dist/bamstats04.jar -B VarDict-amplicon.bed "${pi}/${fn}-bad.bam" > "${pi}/${fn}-bad.coverage"
java -jar /NGS/downloads/jvarkit/dist/bamstats04.jar -B VarDict-amplicon.bed "${pi}/${fn}-cc.bam" > "${pi}/${fn}-cc.coverage"

awk -v filterstr="NT" -v filestr=$fn 'NR==1 {next}{print filterstr "\t" filestr "\t" $1 "\t" $2 "\t" $9 >> "coverage.txt"}' "${pi}/${fn}-NT.coverage"
awk -v filterstr="IS" -v filestr=$fn 'NR==1 {next}{print filterstr "\t" filestr "\t" $1 "\t" $2 "\t" $9 >> "coverage.txt"}' "${pi}/${fn}-IS.coverage"
awk -v filterstr="bad" -v filestr=$fn 'NR==1 {next}{print filterstr "\t" filestr "\t" $1 "\t" $2 "\t" $9 >> "coverage.txt"}' "${pi}/${fn}-bad.coverage"
awk -v filterstr="cc" -v filestr=$fn 'NR==1 {next}{print filterstr "\t" filestr "\t" $1 "\t" $2 "\t" $9 >> "coverage.txt"}' "${pi}/${fn}-cc.coverage"

fi

done < "$input"
